#!/usr/bin/env bash
#
# compose.sh — Assemble a project-specific CLAUDE.md from layers
#
# Usage:
#   ./compose.sh [options] <output_path> <layer1> [layer2] [layer3] ...
#
# Example:
#   ./compose.sh ./CLAUDE.md universal java spring-boot react
#   ./compose.sh ./CLAUDE.md universal java spring-boot kafka
#   ./compose.sh ./CLAUDE.md universal java spark-java
#
# Available layers:
#   universal      — Stack-agnostic engineering standards (writes to ~/.claude/CLAUDE.md)
#   java           — Java/JVM naming and structural conventions
#   spring-boot    — Spring Boot backend standards
#   mysql          — MySQL/JPA/Flyway database standards
#   postgres       — PostgreSQL/JPA/Flyway database standards
#   mongodb        — MongoDB/Spring Data Mongo database standards
#   dynamodb       — DynamoDB/Spring Data DynamoDB database standards
#   react          — React/TypeScript frontend standards
#   kafka          — Apache Kafka messaging standards
#   spark-java     — Apache Spark/Java data processing standards
#   domain         — Domain context (copy TEMPLATE.md, fill in, then reference here)
#
# Options:
#   --user-memory <path>   Write universal layer to this path (default: ~/.claude/CLAUDE.md)
#   --no-user-memory       Write universal content inline into the project file instead
#   --force                Overwrite user memory file even if it contains non-generated content
#
# The script looks for layers in the following locations:
#   ./layers/base/universal.md         (for the universal layer)
#   ./layers/tech/{layer}/CLAUDE.md    (for all other named layers)
#   ./layers/domain/CLAUDE.md          (for the domain layer)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAYERS_DIR="${SCRIPT_DIR}"

SENTINEL="<!-- GENERATED BY claude-docs compose.sh — do not edit directly -->"
USER_MEMORY_PATH="${HOME}/.claude/CLAUDE.md"
NO_USER_MEMORY=false
FORCE=false

# Parse flags
while [[ $# -gt 0 ]]; do
    case "$1" in
        --user-memory)
            USER_MEMORY_PATH="$2"
            shift 2
            ;;
        --no-user-memory)
            NO_USER_MEMORY=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 [options] <output_path> <layer1> [layer2] [layer3] ..."
    echo ""
    echo "Example:"
    echo "  $0 ./CLAUDE.md universal java spring-boot react"
    echo "  $0 ./CLAUDE.md universal java spring-boot kafka"
    echo ""
    echo "Available layers: universal, java, spring-boot, mysql, postgres, mongodb, dynamodb, react, kafka, spark-java, domain"
    echo ""
    echo "Options:"
    echo "  --user-memory <path>   Write universal layer to this path (default: ~/.claude/CLAUDE.md)"
    echo "  --no-user-memory       Write universal content inline into the project file instead"
    echo "  --force                Overwrite user memory even if it contains non-generated content"
    exit 1
fi

OUTPUT_PATH="$1"
shift

LAYERS=("$@")

echo "Composing CLAUDE.md from layers: ${LAYERS[*]}"
echo ""

# Check if universal is in the layer list
HAS_UNIVERSAL=false
for LAYER in "${LAYERS[@]}"; do
    if [[ "$LAYER" == "universal" ]]; then
        HAS_UNIVERSAL=true
        break
    fi
done

UNIVERSAL_FILE="${LAYERS_DIR}/base/universal.md"

# Handle universal layer — write to user memory
if [[ "$HAS_UNIVERSAL" == "true" && "$NO_USER_MEMORY" == "false" ]]; then
    if [[ ! -f "$UNIVERSAL_FILE" ]]; then
        echo "ERROR: Universal layer file not found: $UNIVERSAL_FILE"
        exit 1
    fi

    # Sentinel detection before writing
    if [[ -f "$USER_MEMORY_PATH" && -s "$USER_MEMORY_PATH" ]]; then
        if grep -qF "$SENTINEL" "$USER_MEMORY_PATH"; then
            echo "  Overwriting previously generated user memory: $USER_MEMORY_PATH"
        elif [[ "$FORCE" == "true" ]]; then
            echo "  --force: overwriting existing user memory: $USER_MEMORY_PATH"
        else
            echo ""
            echo "ERROR: $USER_MEMORY_PATH exists and contains content not generated by compose.sh."
            echo "  To overwrite it, re-run with --force."
            echo "  To write universal content into the project file instead, use --no-user-memory."
            exit 1
        fi
    fi

    mkdir -p "$(dirname "$USER_MEMORY_PATH")"
    cp "$UNIVERSAL_FILE" "$USER_MEMORY_PATH"
    echo "  Writing universal standards to: $USER_MEMORY_PATH"
fi

# Clear output file
> "$OUTPUT_PATH"

# Add header
cat >> "$OUTPUT_PATH" << 'HEADER'
<!-- ============================================================
     PROJECT CLAUDE.md
     Composed from Claude Code Starter Kit layers.
     Generated by compose.sh — do not edit the layer sections
     directly. Edit the source layers and recompose.
     ============================================================ -->

HEADER

# Process all layers (universal is skipped unless --no-user-memory)
for LAYER in "${LAYERS[@]}"; do
    LAYER_FILE=""

    case "$LAYER" in
        universal)
            if [[ "$NO_USER_MEMORY" == "true" ]]; then
                LAYER_FILE="${LAYERS_DIR}/base/universal.md"
            else
                # Already written to user memory above — skip
                continue
            fi
            ;;
        domain)
            LAYER_FILE="${LAYERS_DIR}/domain/CLAUDE.md"
            ;;
        *)
            LAYER_FILE="${LAYERS_DIR}/tech/${LAYER}/CLAUDE.md"
            ;;
    esac

    if [[ ! -f "$LAYER_FILE" ]]; then
        echo "ERROR: Layer file not found: $LAYER_FILE"
        echo "  Did you mean one of: universal, java, spring-boot, mysql, postgres, mongodb, dynamodb, react, kafka, spark-java, domain?"
        exit 1
    fi

    echo "  Adding layer: $LAYER ($LAYER_FILE)"

    # Add section separator and layer content
    cat >> "$OUTPUT_PATH" << SEPARATOR

<!-- ============================================================
     LAYER: ${LAYER}
     Source: ${LAYER_FILE}
     ============================================================ -->

SEPARATOR

    cat "$LAYER_FILE" >> "$OUTPUT_PATH"
    echo "" >> "$OUTPUT_PATH"
done

# Append PROJECT ADDITIONS footer
cat >> "$OUTPUT_PATH" << 'ADDITIONS'

<!-- ============================================================
     PROJECT ADDITIONS
     Add project-specific conventions below this line.
     To promote a convention to the claude-docs kit, run /promote.
     ============================================================ -->

ADDITIONS

echo ""

# Summary output
if [[ "$HAS_UNIVERSAL" == "true" && "$NO_USER_MEMORY" == "false" ]]; then
    USER_MEM_LINES=$(wc -l < "$USER_MEMORY_PATH" | tr -d ' ')
    echo "User standards written to:  $USER_MEMORY_PATH ($USER_MEM_LINES lines)"
fi

PROJECT_LINES=$(wc -l < "$OUTPUT_PATH" | tr -d ' ')

# Build project layers list (exclude universal unless --no-user-memory)
PROJECT_LAYERS=()
for LAYER in "${LAYERS[@]}"; do
    if [[ "$LAYER" != "universal" || "$NO_USER_MEMORY" == "true" ]]; then
        PROJECT_LAYERS+=("$LAYER")
    fi
done

echo "Project CLAUDE.md written to: $OUTPUT_PATH ($PROJECT_LINES lines)"
echo "Layers included:              ${PROJECT_LAYERS[*]}"
