#!/usr/bin/env bash
#
# compose.sh — Assemble a project-specific CLAUDE.md from layers
#
# Usage:
#   ./compose.sh [output_path] [layer1] [layer2] [layer3] ...
#
# Example:
#   ./compose.sh ./CLAUDE.md base spring-boot react
#   ./compose.sh ./CLAUDE.md base spring-boot kafka
#   ./compose.sh ./CLAUDE.md base spark-java
#
# Available layers:
#   base           — Universal engineering standards (always include this)
#   spring-boot    — Spring Boot backend standards
#   mysql          — MySQL/JPA/Flyway database standards
#   postgres       — PostgreSQL/JPA/Flyway database standards
#   mongodb        — MongoDB/Spring Data Mongo database standards
#   dynamodb       — DynamoDB/Spring Data DynamoDB database standards
#   react          — React/TypeScript frontend standards
#   kafka          — Apache Kafka messaging standards
#   spark-java     — Apache Spark/Java data processing standards
#   domain         — Domain context (copy TEMPLATE.md, fill in, then reference here)
#
# The script looks for layers in the following locations:
#   ./layers/base/CLAUDE.md
#   ./layers/tech/{layer}/CLAUDE.md
#   ./layers/domain/CLAUDE.md (for domain layer)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAYERS_DIR="${SCRIPT_DIR}"

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <output_path> <layer1> [layer2] [layer3] ..."
    echo ""
    echo "Example:"
    echo "  $0 ./CLAUDE.md base spring-boot react"
    echo "  $0 ./CLAUDE.md base spring-boot kafka"
    echo ""
    echo "Available layers: base, spring-boot, mysql, postgres, mongodb, dynamodb, react, kafka, spark-java, domain"
    exit 1
fi

OUTPUT_PATH="$1"
shift

echo "Composing CLAUDE.md from layers: $*"
echo ""

# Clear output file
> "$OUTPUT_PATH"

# Add header
cat >> "$OUTPUT_PATH" << 'HEADER'
<!-- ============================================================
     PROJECT CLAUDE.md
     Composed from Claude Code Starter Kit layers.
     Generated by compose.sh — do not edit the layer sections
     directly. Edit the source layers and recompose.
     ============================================================ -->

HEADER

for LAYER in "$@"; do
    LAYER_FILE=""

    case "$LAYER" in
        base)
            LAYER_FILE="${LAYERS_DIR}/base/CLAUDE.md"
            ;;
        domain)
            LAYER_FILE="${LAYERS_DIR}/domain/CLAUDE.md"
            ;;
        *)
            LAYER_FILE="${LAYERS_DIR}/tech/${LAYER}/CLAUDE.md"
            ;;
    esac

    if [[ ! -f "$LAYER_FILE" ]]; then
        echo "ERROR: Layer file not found: $LAYER_FILE"
        echo "  Did you mean one of: base, spring-boot, mysql, postgres, mongodb, dynamodb, react, kafka, spark-java, domain?"
        exit 1
    fi

    echo "  Adding layer: $LAYER ($LAYER_FILE)"

    # Add section separator and layer content
    cat >> "$OUTPUT_PATH" << SEPARATOR

<!-- ============================================================
     LAYER: ${LAYER}
     Source: ${LAYER_FILE}
     ============================================================ -->

SEPARATOR

    cat "$LAYER_FILE" >> "$OUTPUT_PATH"
    echo "" >> "$OUTPUT_PATH"
done

echo ""
echo "Composed CLAUDE.md written to: $OUTPUT_PATH"
echo "Layers included: $*"

# Show file size
SIZE=$(wc -c < "$OUTPUT_PATH" | tr -d ' ')
LINES=$(wc -l < "$OUTPUT_PATH" | tr -d ' ')
echo "Size: ${SIZE} bytes, ${LINES} lines"
